import Post from '@/types/Post';

const featuredPosts: Post[] = [
  { id: 1, thumb: '/imgs/featured-post-temp-img.jpg', thumbAlt: 'Imagem de thumb', miniature: '/imgs/temp-miniature.jpg', tags: ['Machine Learning', 'Data Science', 'Python'], title: 'Quantum Computing: Desvendando a Revolução Digital', description: 'Biodesign: A Fusão Criativa entre Biologia e Tecnologia, Transformando Produtos e Experiências para um Futuro Sustentável', postUrl: '/', date: '05/02/2023', views: 573, likes: 56 },
  { id: 2, thumb: '/imgs/featured-post-temp-img.jpg', thumbAlt: 'Imagem de thumb', miniature: '/imgs/temp-miniature.jpg', tags: ['Blockchain', 'Cryptocurrency', 'Smart Contracts'], title: 'Desvendando o Mistério da Criptografia Quântica: Segurança Impenetrável em Redes ultra modernas', description: 'A Era dos Veículos Voadores: Tecnologia Alçando Novos Horizontes', postUrl: '/', date: '21/03/2023', views: 1245, likes: 122 },
  { id: 3, thumb: '/imgs/featured-post-temp-img.jpg', thumbAlt: 'Imagem de thumb', miniature: '/imgs/temp-miniature.jpg', tags: ['Augmented Reality', 'VR', 'Immersive Tech'], title: 'Realidade Aumentada: Além do que os olhos veem', description: 'Inteligência Artificial Ética: Explorando Abordagens para Garantir Decisões Justas e Imparciais em Sistemas Autônomos', postUrl: '/', date: '08/05/2023', views: 1987, likes: 189 },
  { id: 4, thumb: '/imgs/featured-post-temp-img.jpg', thumbAlt: 'Imagem de thumb', miniature: '/imgs/temp-miniature.jpg', tags: ['Cybersecurity', 'Threat Detection', 'Encryption'], title: 'Inteligência Artificial na Educação: Transformando a Sala de Aula Tradicional', description: 'Robôs na Saúde: Transformando o Cuidado com a Medicina de Precisão', postUrl: '/', date: '17/07/2023', views: 832, likes: 45 },
  { id: 5, thumb: '/imgs/featured-post-temp-img.jpg', thumbAlt: 'Imagem de thumb', miniature: '/imgs/temp-miniature.jpg', tags: ['Quantum Computing', 'Qubits', 'Superposition'], title: 'Inteligência Artificial na Medicina: Curando com Algoritmos', description: 'Realidade Virtual no Trabalho: Como a VR está Redefinindo o Escritório', postUrl: '/', date: '02/09/2023', views: 2670, likes: 267 },
  { id: 6, thumb: '/imgs/featured-post-temp-img.jpg', thumbAlt: 'Imagem de thumb', miniature: '/imgs/temp-miniature.jpg', tags: ['IoT', 'Smart Cities', 'Connected Devices'], title: 'Blockchain Descomplicado: Do Bitcoin às Aplicações Empresariais', description: 'Desvendando a Singularidade Tecnológica: Rumo a uma Era de Máquinas Superinteligentes e Transformações Inimagináveis', postUrl: '/', date: '19/10/2023', views: 1498, likes: 148 },
  { id: 7, thumb: '/imgs/featured-post-temp-img.jpg', thumbAlt: 'Imagem de thumb', miniature: '/imgs/temp-miniature.jpg', tags: ['Biotechnology', 'Genomics', 'Bioengineering'], title: 'Robôs Colaborativos: Trabalhando Juntos para o Futuro', description: 'Drones de Entrega: A Logística do Futuro nas Asas da Inovação', postUrl: '/', date: '28/12/2023', views: 521, likes: 23 },
  { id: 8, thumb: '/imgs/featured-post-temp-img.jpg', thumbAlt: 'Imagem de thumb', miniature: '/imgs/temp-miniature.jpg', tags: ['Space Exploration', 'Satellites', 'Astrophysics'], title: '5G e a Conexão Ultrarrápida: Transformando a Comunicação', description: 'Blockchain Além das Criptomoedas: Transformando Indústrias, Garantindo Transparência e Facilitando a Colaboração Global', postUrl: '/', date: '14/02/2023', views: 2035, likes: 203 },
  { id: 9, thumb: '/imgs/featured-post-temp-img.jpg', thumbAlt: 'Imagem de thumb', miniature: '/imgs/temp-miniature.jpg', tags: ['3D Printing', 'Additive Manufacturing', 'Materials Science'], title: 'Cibersegurança 2.0: Protegendo-se contra Ameaças Avançadas', description: 'Cidades Inteligentes 2.0: Integrando Tecnologias Avançadas para Criar Ambientes Urbanos Mais Eficientes e Sustentáveis', postUrl: '/', date: '03/04/2023', views: 1476, likes: 147 },
  { id: 10, thumb: '/imgs/featured-post-temp-img.jpg', thumbAlt: 'Imagem de thumb', miniature: '/imgs/temp-miniature.jpg', tags: ['Artificial General Intelligence', 'Ethics in AI', 'AGI'], title: 'A Revolução dos Veículos Autônomos: Da Ficção à Realidade Conduzida pela Tecn', description: 'A Revolução dos Assistentes Virtuais: Além da Siri e Alexa', postUrl: '/', date: '22/06/2023', views: 1189, likes: 118 },
  { id: 11, thumb: '/imgs/featured-post-temp-img.jpg', thumbAlt: 'Imagem de thumb', miniature: '/imgs/temp-miniature.jpg', tags: ['Renewable Energy', 'Green Tech', 'Sustainability'], title: 'IoT na Agricultura: Colhendo Dados para Colher Sucessos', description: 'Criptomoedas 2023: Navegando na Onda Digital dos Ativos Virtuais', postUrl: '/', date: '09/08/2023', views: 2847, likes: 284 },
  { id: 12, thumb: '/imgs/featured-post-temp-img.jpg', thumbAlt: 'Imagem de thumb', miniature: '/imgs/temp-miniature.jpg', tags: ['Human-Computer Interaction', 'User Experience', 'Interface Design'], title: 'Conectando Mentes e Máquinas: A Ascensão da Interface Cérebro-Computador', description: 'Neurotecnologia: Desbravando o Cérebro Digital para Entender e Potencializar Nossa Mente, Saúde e Desempenho Cognitivo', postUrl: '/', date: '27/09/2023', views: 690, likes: 69 },
];

export default featuredPosts;
