spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
api:
  security:
    token:
      secret: ${JWT_TOKEN_SECRET}
      expiresAt: ${JWT_EXPIRES_AT}
      issuer: ${JWT_ISSUER}
    cors:
      originPatterns: ${AUTHORIZED_URLS_SEPARATED_BY_COMMA}
